/**
 * Option sets for the {{Entity.DisplayName}} entity.
 *
 * This code was generated by a tool
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 *
 */
{{#OptionSets}}export const {{Entity.LogicalName}}OptionSet_{{OptionSet.AttributeLogicalName}} = {
{{#Options}}    {{Option.Key}}: {{Option.Value}}{{Option.Comma}}
{{/Options}}} as const;

{{/OptionSets}}
export const {{Entity.LogicalName}}OptionSets = {
{{#OptionSets}}    {{OptionSet.AttributeKey}}: {{Entity.LogicalName}}OptionSet_{{OptionSet.AttributeLogicalName}}{{OptionSet.Comma}}
{{/OptionSets}}} as const;
