/**
 * The {{Entity.LogicalName}} class defines metadata for the {{Entity.DisplayName}} entity.
 *
 * This code was generated by a tool
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 *
 */
export class {{Entity.LogicalName}} {
    public static EntitySchemaName = "{{Entity.SchemaName}}";
    public static EntityLogicalName = "{{Entity.LogicalName}}";

    public static attributes = {
{{#Attributes}}        {{Attribute.Key}}: {
            SchemaName: "{{Attribute.SchemaName}}",
            LogicalName: "{{Attribute.LogicalName}}",
        }{{Attribute.Comma}}
{{/Attributes}}    };
}
